/* config/shore-config.h.  Generated by configure.  */
/* config/shore-config-h.in.  Generated from configure.ac by autoheader.  */

/* operating system */
/* #undef AIX32 */

/* operating system */
/* #undef AIX41 */

/* for ia64 only */
/* #undef ARCH_LP64 */

/* architecture */
/* #undef Alpha */

/* is gcc 2.96 */
/* #undef GCC_BROKEN_WARNINGS */

/* hack for gcc3.4 and later */
/* #undef GCC_VER_34_WARNINGS */

/* is gcc 3.x, x < 4 */
/* #undef GCC_VER_3_WARNINGS */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `c' library (-lc). */
#define HAVE_LIBC 1

/* Define to 1 if you have the `tcl' library (-ltcl). */
/* #undef HAVE_LIBTCL */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if `st_blksize' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/timeb.h> header file. */
#define HAVE_SYS_TIMEB_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1

/* operating system */
/* #undef HPUX8 */

/* architecture */
#define I386 

/* architecture */
/* #undef I860 */

/* architecture */
/* #undef IA64 */

/* aix */
/* #undef IS_AIX */

/* aix3 */
/* #undef IS_AIX3 */

/* aix41 */
/* #undef IS_AIX4 */

/* osf1 alpha */
/* #undef IS_ALPHA_OSF1 */

/* nt cygwin */
/* #undef IS_CYGWIN */

/* dos-based */
/* #undef IS_DOSDEV */

/* hp unix */
/* #undef IS_HPUX8 */

/* x86 nt cygwin */
/* #undef IS_I386_CYGWIN */

/* i386 linux */
#define IS_I386_LINUX 1

/* i386 macosx */
/* #undef IS_I386_MACOSX */

/* i386 netbsd */
/* #undef IS_I386_NETBSD */

/* is solaris */
/* #undef IS_I386_SOLARIS2 */

/* osf1 paragon */
/* #undef IS_I860_OSF1AD */

/* ia64 linux */
/* #undef IS_IA64_LINUX */

/* irix */
/* #undef IS_IRIX */

/* x86 nt */
/* #undef IS_IX86_NT */

/* linux */
#define IS_LINUX 1

/* apple mac osx */
/* #undef IS_MACOSX */

/* sgi mips irix */
/* #undef IS_MIPS_IRIX */

/* mips ultrix */
/* #undef IS_MIPS_ULTRIX42 */

/* netbsd */
/* #undef IS_NETBSD */

/* is nt */
/* #undef IS_NT */

/* osf1 */
/* #undef IS_OSF1 */

/* osf1 */
/* #undef IS_OSF1AD */

/* powerpc macosx */
/* #undef IS_POWERPC_MACOSX */

/* Rs6000 aix32 */
/* #undef IS_RS6000_AIX32 */

/* Rs6000 aix41 */
/* #undef IS_RS6000_AIX41 */

/* hp unix */
/* #undef IS_SNAKE_HPUX8 */

/* sparc solaris */
/* #undef IS_SOLARIS2 */

/* is solaris */
/* #undef IS_SPARC_SOLARIS2 */

/* is not solaris */
/* #undef IS_SPARC_SUNOS41 */

/* not solaris */
/* #undef IS_SUNOS41 */

/* ultrix */
/* #undef IS_ULTRIX42 */

/* windows or unix? */
/* #undef IS_UNIX */

/* operating system */
/* #undef Irix */

/* enable use of pages larger than 32K? */
#define LARGEPAGES 0

/* use large page ids? */
#define LARGEVOLUMES 0

/* operating system */
#define Linux 

/* operating system */
/* #undef MacOSX */

/* architecture */
/* #undef Mips */

/* does compiler have header-file pedantic-errors */
/* #undef NOPEDANTIC */

/* operating system */
/* #undef OSF1 */

/* operating system */
/* #undef OSF1AD */

/* Name of package */
#define PACKAGE "shore-storage-manager"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Noone._Sadly-_this_is_unsupported_software."

/* Define to the full name of this package. */
#define PACKAGE_NAME "Shore-Storage-Manager"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Shore-Storage-Manager 5.0.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "shore-storage-manager"

/* Define to the version of this package. */
#define PACKAGE_VERSION "5.0.3"

/* architecture */
/* #undef PowerPC */

/* architecture */
/* #undef Rs6000 */

/* operating system */
/* #undef SOLARIS2 */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* operating system */
/* #undef SUNOS41 */

/* architecture */
/* #undef Snake */

/* architecture */
/* #undef Sparc */

/* include tracing code? */
#define TRACECODE 0

/* operating system */
/* #undef Ultrix42 */

/* Version number of package */
#define VERSION "5.0.3"

/* use large files? */
#define W_LARGEFILE 1

/* tracing debugging code included */
/* #undef W_TRACE */

/* operating system */
/* #undef __MacOSX__ */


#define SM_DISKADDR_LARGE 1


/*for thread statistics*/
#define EXPENSIVE_STATS


/*if is gcc 2.96*/
#if defined(__GNUC__) && __GNUC__==2
# if defined(__GNUC_MINOR__) && __GNUC_MINOR__==96
# define GCC_BROKEN_WARNINGS
#endif
#endif


/*if is gcc3.x, x < 4*/
#if defined(__GNUC__) && (__GNUC__==3)
# define GCC_VER_3_WARNINGS
#endif


/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/*turn off hpux and hp9000s800*/
#if defined(hpux) && defined(hp9000s800)
/* #undef hpux */
/* #undef hp9000s800 */
#endif


/* architecture - not always defined by compiler */
#define i386 1

/*simply !IS_NT*/
#ifndef IS_NT
#define IS_UNIX 1
#endif


#ifdef W_LARGEFILE
#define _FILE_OFFSET_BITS 64
#define LARGEFILE_AWARE
#endif


#if LARGEPAGES==1
#define LARGE_PAGE
#endif


#if LARGEVOLUMES==1
#define LARGE_PID
#endif


/*turn off mips and ultrix*/
#if defined(mips) && defined(ultrix)
/* #undef mips */
/* #undef ultrix */
#endif


/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/*turn off sgi */
#if defined(sgi)
/* #undef sgi */
#endif


/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/*1024 to 32768 inclusive*/
#ifndef SM_PAGESIZE
#define SM_PAGESIZE 8192
#endif


/*0, 1 or 2*/
#ifndef STHREAD_STACK_CHECK
#ifdef W_DEBUG
#define STHREAD_STACK_CHECK 2
#else
#define STHREAD_STACK_CHECK 1
#endif
#endif


/*turn off sun and sparc*/
#if defined(sun) && defined(sparc)
/* #undef sun */
/* #undef sparc */
#endif


#if TRACECODE==1
#define W_TRACE
#endif


/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */

/*for in-memory str streams*/
#define W_USE_COMPAT_STRSTREAM


/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */

/* ultrix */
/* #undef w_NetBSD */

/* operating system */
/* #undef win32 */
