#!/bin/sh

#
# This program should be run in the betadoc/docs/man after all the
# .html pages are inserted.  It generates a file, contents.html, listing
#  all man pages (as hyperlinks).
#

O=contents.html
echo "<HEAD>" > $O
echo "<TITLE>" >> $O
echo "CONTENTS -- <em>Shore Programmer's Manual</em> -" \
	`date "+%d %B %y"` >> $O
echo "</TITLE></HEAD>" >> $O

echo "<BODY>" >> $O
echo "<H1>CONTENTS</H1>" >> $O
echo "<H2><em>Shore Programmer's Manual</em> -" \
	`date "+%d %B %y"` "</H2>" >> $O

cat <<EOF >>$O
<H2>NAME</H2>
Table of Contents -- List of all Manual Pages
<H2>SYNOPSIS</H2>
EOF

/bin/ls *.html | gawk >>$O '
{
	printf "<p><a href=%c%s%c>%s</a>\n", 34, $1, 34, $1
}'

cat <<EOF >>$O
<H2>VERSION</H2>
This manual page applies to Version 0.2 (Beta) of the Shore software.
<H2>SPONSORSHIP</H2>
The Shore project is sponsored by the Advanced Research Project Agency, ARPA
order number 018 (formerly 8230), monitored by the U.S. Army Research
Laboratory under contract DAAB07-91-C-Q518.
<H2>COPYRIGHT</H2>
Copyright (c) 1994, 1995 Computer Sciences Department, University of Wisconsin -- Madison. All Rights Reserved.
</BODY>
EOF
